# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  tag: '$(Build.BuildId)'
  imageName: 'frederikvolkers/chpt3:$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: |
                $(dockerHub)
              repository: $(imageName)
              command: build
              dockerfile: '$(Build.SourcesDirectory)/sizeapp/Dockerfile'
              buildContext: '.'
          - task: Docker@2
            displayName: Push an image to container registry
            inputs:
              containerRegistry: |
                $(dockerHub)
              repository: $(imageName)
              command: push

            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
